//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trans_KYCDetails
    {
        public int ID { get; set; }
        public string PanNo { get; set; }
        public string AdhaarNo { get; set; }
        public string CustomerID { get; set; }
        public Nullable<System.DateTime> KYCDate { get; set; }
        public string ApplicationNo { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ApplicantPrefix { get; set; }
        public string ApplicantName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Father_Spouse { get; set; }
        public string Father_SpouseName { get; set; }
        public string MotherName { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Age { get; set; }
        public string CKYCNo { get; set; }
        public string MaritalStatus { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string Emailid { get; set; }
        public string SourceOfApplication { get; set; }
        public string SourceType { get; set; }
        public string ExistingPLCaseNo { get; set; }
        public string PresentAnnualIncome { get; set; }
        public string OccupationType { get; set; }
        public string OccupationOther { get; set; }
        public string Designation { get; set; }
        public string NameofOrganization { get; set; }
        public string Industrytype { get; set; }
        public string IndustryOther { get; set; }
        public string NomineeName { get; set; }
        public string NomineeAddress { get; set; }
        public string NomineeMobileNo { get; set; }
        public string NomineeRelationship { get; set; }
        public string NomineePanNo { get; set; }
        public string NomineeAdharNo { get; set; }
        public string DocumentName { get; set; }
        public string DocumentOther { get; set; }
        public string Nameondocument { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public string DocumentURL { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
